/** Electromon state code → INEC portal numeric state id (matches official IReV URLs). */
export const IREV_STATE_INEC_IDS: Record<string, number> = {
  AB: 1,
  AD: 2,
  AK: 3,
  AN: 4,
  BA: 5,
  BY: 6,
  BE: 7,
  BO: 8,
  CR: 9,
  DE: 10,
  EB: 11,
  ED: 12,
  EK: 13,
  EN: 14,
  FC: 15,
  GO: 16,
  IM: 17,
  JI: 18,
  KD: 19,
  KN: 20,
  KT: 21,
  KE: 22,
  KO: 23,
  KW: 24,
  LA: 25,
  NA: 26,
  NI: 27,
  OG: 28,
  ON: 29,
  OS: 30,
  OY: 31,
  PL: 32,
  RI: 33,
  SO: 34,
  TA: 35,
  YO: 36,
  ZA: 37,
};

export function inecStateIdForCode(stateCode: string): number | null {
  return IREV_STATE_INEC_IDS[stateCode.toUpperCase()] ?? null;
}
