export enum CampaignRole {
  CANDIDATE = 'CANDIDATE',
  CAMPAIGN_DIRECTOR = 'CAMPAIGN_DIRECTOR',
  /** @deprecated Use STATE_COLLATION_OFFICER — kept for existing DB rows */
  STATE_COORDINATOR = 'STATE_COORDINATOR',
  /** @deprecated Use LGA_COLLATION_OFFICER — kept for existing DB rows */
  LGA_COORDINATOR = 'LGA_COORDINATOR',
  /** @deprecated Use WARD_RA_OFFICER — kept for existing DB rows */
  WARD_COORDINATOR = 'WARD_COORDINATOR',
  SUPPORT_GROUP_LEADER = 'SUPPORT_GROUP_LEADER',
  VOLUNTEER_COORDINATOR = 'VOLUNTEER_COORDINATOR',
  POLLING_AGENT_COORDINATOR = 'POLLING_AGENT_COORDINATOR',
  DATA_ANALYST = 'DATA_ANALYST',
  MEDIA_TEAM = 'MEDIA_TEAM',
  POLLING_AGENT = 'POLLING_AGENT',
  VOLUNTEER = 'VOLUNTEER',
  /** @deprecated Use POLLING_AGENT — kept for existing DB rows */
  POLLING_UNIT_OFFICER = 'POLLING_UNIT_OFFICER',
  WARD_RA_OFFICER = 'WARD_RA_OFFICER',
  LGA_COLLATION_OFFICER = 'LGA_COLLATION_OFFICER',
  STATE_COLLATION_OFFICER = 'STATE_COLLATION_OFFICER',
  NATIONAL_COLLATION_OFFICER = 'NATIONAL_COLLATION_OFFICER',
}

/** Canonical collation hierarchy — one role per level */
export const LEVEL_ROLES = {
  POLLING_UNIT: CampaignRole.POLLING_AGENT,
  WARD: CampaignRole.WARD_RA_OFFICER,
  LGA: CampaignRole.LGA_COLLATION_OFFICER,
  STATE: CampaignRole.STATE_COLLATION_OFFICER,
  NATIONAL: CampaignRole.NATIONAL_COLLATION_OFFICER,
} as const;

export enum ScopeType {
  STATE = 'STATE',
  SENATORIAL_DISTRICT = 'SENATORIAL_DISTRICT',
  LGA = 'LGA',
  CONSTITUENCY = 'CONSTITUENCY',
  WARD = 'WARD',
  POLLING_UNIT = 'POLLING_UNIT',
  CAMPAIGN = 'CAMPAIGN',
  NATIONAL = 'NATIONAL',
}

export enum ContestType {
  GOVERNORSHIP = 'GOVERNORSHIP',
  ASSEMBLY = 'ASSEMBLY',
}

export enum SupportGroupCategory {
  YOUTH = 'YOUTH',
  WOMEN = 'WOMEN',
  FARMERS = 'FARMERS',
  PROFESSIONALS = 'PROFESSIONALS',
  STUDENTS = 'STUDENTS',
  RELIGIOUS = 'RELIGIOUS',
  COMMUNITY = 'COMMUNITY',
}

export enum VerificationStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  ACTIVE = 'ACTIVE',
  REJECTED = 'REJECTED',
}

export enum FieldReportType {
  SECURITY_CONCERN = 'SECURITY_CONCERN',
  COMMUNITY_REQUEST = 'COMMUNITY_REQUEST',
  OPPOSITION_ACTIVITY = 'OPPOSITION_ACTIVITY',
  CAMPAIGN_PROGRESS = 'CAMPAIGN_PROGRESS',
  DAILY_SITREP = 'DAILY_SITREP',
  INCIDENT = 'INCIDENT',
}

export enum IncidentType {
  VOTER_INTIMIDATION = 'VOTER_INTIMIDATION',
  BALLOT_SNATCHING = 'BALLOT_SNATCHING',
  BALLOT_STUFFING = 'BALLOT_STUFFING',
  VOTE_BUYING = 'VOTE_BUYING',
  VIOLENCE_THUGGERY = 'VIOLENCE_THUGGERY',
  MATERIALS_SHORTAGE = 'MATERIALS_SHORTAGE',
  LATE_OR_FAILED_OPENING = 'LATE_OR_FAILED_OPENING',
  BVAS_MALFUNCTION = 'BVAS_MALFUNCTION',
  UNAUTHORIZED_PERSONNEL = 'UNAUTHORIZED_PERSONNEL',
  OVERVOTING = 'OVERVOTING',
  OPPOSITION_DISRUPTION = 'OPPOSITION_DISRUPTION',
  OTHERS = 'OTHERS',
}

export enum IncidentSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export function isIncidentSeverityUrgent(severity: IncidentSeverity): boolean {
  return severity === IncidentSeverity.HIGH || severity === IncidentSeverity.CRITICAL;
}

export enum FieldReportStatus {
  OPEN = 'OPEN',
  ESCALATED = 'ESCALATED',
  RESOLVED = 'RESOLVED',
}

export enum PollingUnitStrength {
  STRONG = 'STRONG',
  SWING = 'SWING',
  WEAK = 'WEAK',
}

export enum PollingUnitStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  NEEDS_ATTENTION = 'NEEDS_ATTENTION',
}

export enum SituationStatus {
  OPEN = 'OPEN',
  REPORTING = 'REPORTING',
  CLOSED = 'CLOSED',
  INCIDENT = 'INCIDENT',
}

export enum ElectionDayPhase {
  CHECKED_IN = 'CHECKED_IN',
  MATERIALS_READY = 'MATERIALS_READY',
  OPENED = 'OPENED',
  VOTING = 'VOTING',
  CLOSED = 'CLOSED',
  COUNTING = 'COUNTING',
}

export enum PulseAtmosphere {
  CALM = 'CALM',
  TENSE = 'TENSE',
  DISRUPTED = 'DISRUPTED',
}

export enum PulseBvasStatus {
  WORKING = 'WORKING',
  SLOW = 'SLOW',
  DOWN = 'DOWN',
  NOT_SEEN = 'NOT_SEEN',
}

export enum PulseQueue {
  NONE = 'NONE',
  SHORT = 'SHORT',
  LONG = 'LONG',
}

export enum PulseTurnoutBand {
  LOW = 'LOW',
  NORMAL = 'NORMAL',
  HIGH = 'HIGH',
}

export enum RivalMobilization {
  NONE = 'NONE',
  LIGHT = 'LIGHT',
  HEAVY = 'HEAVY',
}

export enum CrowdLean {
  OURS = 'OURS',
  THEIRS = 'THEIRS',
  MIXED = 'MIXED',
  THIN = 'THIN',
}

export enum WhoLooksAhead {
  US = 'US',
  RIVAL = 'RIVAL',
  UNCLEAR = 'UNCLEAR',
}

export enum RivalTactic {
  INDUCEMENT = 'INDUCEMENT',
  INTIMIDATION = 'INTIMIDATION',
  QUEUE_STACKING = 'QUEUE_STACKING',
  UNAUTHORIZED_PERSONNEL = 'UNAUTHORIZED_PERSONNEL',
  PARALLEL_STRUCTURE = 'PARALLEL_STRUCTURE',
  LEGAL_MEDIA_PRESENT = 'LEGAL_MEDIA_PRESENT',
  DISRUPTION = 'DISRUPTION',
}

export enum ObservedConfidence {
  WATCHING = 'WATCHING',
  PARTIAL = 'PARTIAL',
  NEAR_FINAL = 'NEAR_FINAL',
}

export enum PulseSource {
  MANUAL = 'MANUAL',
  CHECK_IN = 'CHECK_IN',
  HEARTBEAT = 'HEARTBEAT',
  RESULT = 'RESULT',
  INCIDENT = 'INCIDENT',
}

export const PULSE_SILENT_MINUTES = 45;

export enum NotificationType {
  RESULT_SUBMITTED = 'RESULT_SUBMITTED',
  RESULT_APPROVED = 'RESULT_APPROVED',
  RESULT_RETURNED = 'RESULT_RETURNED',
  RESULT_COMMENTED = 'RESULT_COMMENTED',
  WARD_RETURNED_BY_LGA = 'WARD_RETURNED_BY_LGA',
  WARD_FORWARDED_TO_LGA = 'WARD_FORWARDED_TO_LGA',
  INCIDENT_REPORTED = 'INCIDENT_REPORTED',
  INCIDENT_RESOLVED = 'INCIDENT_RESOLVED',
  INCIDENT_ESCALATED = 'INCIDENT_ESCALATED',
  SITUATION_UPDATE = 'SITUATION_UPDATE',
  TRIAGE_RISK_RAISED = 'TRIAGE_RISK_RAISED',
  TRIAGE_RISK_CLEARED = 'TRIAGE_RISK_CLEARED',
  PULSE_REMINDER = 'PULSE_REMINDER',
}

export enum NotificationPriority {
  LOW = 'LOW',
  NORMAL = 'NORMAL',
  HIGH = 'HIGH',
}

export enum DevicePlatform {
  ANDROID = 'ANDROID',
  IOS = 'IOS',
}

export enum SocialPlatform {
  FACEBOOK = 'FACEBOOK',
  X = 'X',
  TIKTOK = 'TIKTOK',
  WHATSAPP = 'WHATSAPP',
  OTHER = 'OTHER',
}

export enum SocialSentiment {
  POSITIVE = 'POSITIVE',
  NEUTRAL = 'NEUTRAL',
  NEGATIVE = 'NEGATIVE',
  MIXED = 'MIXED',
  UNKNOWN = 'UNKNOWN',
}

export enum TriageOutlook {
  WINNING = 'WINNING',
  LEANING_WIN = 'LEANING_WIN',
  TOSSUP = 'TOSSUP',
  LEANING_LOSS = 'LEANING_LOSS',
  LOSING = 'LOSING',
  UNKNOWN = 'UNKNOWN',
}

export enum TriageRiskLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export const MFA_REQUIRED_ROLES: CampaignRole[] = [
  CampaignRole.CANDIDATE,
  CampaignRole.CAMPAIGN_DIRECTOR,
  CampaignRole.STATE_COLLATION_OFFICER,
  CampaignRole.NATIONAL_COLLATION_OFFICER,
];
